[package]
name = "semantic-search"
version = "0.1.0"
edition = "2021"

[[bin]]
name= "search"
path = "src/search.rs"

[[bin]]
name= "index"
path = "src/index.rs"

[[bin]]
name= "convertembeddings"
path = "src/convertembeddings.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "^0.21.0"
flate2 = "1.0.26"
url = "2.4.0"
memmap2 = "0.7.1"
whichlang = "0.1.0"
indicatif = "0.17.5"
tch = "^0.13.0"
torch-sys = "^0.13.0"
readability = "0.2.0"
anyhow = "1.0.72"
