[package]
name = "arecibo"
version = "0.0.0"
edition = "2021"

[lib]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "^0.21.0"
flate2 = "1.0.26"
url = "2.4.0"
memmap2 = "0.7.1"
whichlang = "0.1.0"
indicatif = "0.17.5"
tch = "^0.13.0"
torch-sys = "^0.13.0"
readability = "0.2.0"
anyhow = "1.0.72"
ureq = "2.7.1"
html5ever = "0.25"
markup5ever_rcdom = "0.1"
postgres = "0.19.5"
rand = "0.8.5"
num = "0.4.1"
usearch = "0.22.3"
